### ISSUE TITLE
sensitivity ratio plots

### ISSUE THREAD

**Issue by rxa254** [artificial-scientist-lab/GWDetectorZoo#1]
in some cases, where the noise curves are close, in addition to plotting the strain noise, it would be good to also have a plot of the ratio of each plot w.r.t. the baseline curves, so that one can see the improvement explicitly.

**Comment by MarioKrenn6240** [comment]
Great suggestion, will add this.

**Comment by MarioKrenn6240** [comment]
Finally implemented. Looks very good, even for detectors where the log-plot hides the improvement.
